name: Build Package

on:
  push:
    branches: [master]
    tags:
      - v*

env:
  IMAGE_NAME: resume

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Build Package
        run: docker build . --tag $IMAGE_NAME
      - name: Log into Lucemans registry
        run: echo "${{ secrets.LVK_REGISTRY }}" | docker login lvk.sh -u lucemans --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=lvk.sh/resume

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION