name: Build & Deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  PACKAGE_NAME: lvk.sh/resume

jobs:
  build:
    runs-on: ubuntu-20.04
    name: 🔨 Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Build Package
        run: docker build --build-arg VERSION="${{ github.sha }}" . --tag ${{ env.PACKAGE_NAME }}
      - name: Log into Lucemans registry
        run: echo "${{ secrets.LVK_REGISTRY }}" | docker login lvk.sh -u lucemans --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=${{ env.PACKAGE_NAME }}

          VERSION=$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')

          echo $IMAGE_ID
          echo $VERSION

          docker tag ${{ env.PACKAGE_NAME }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  terraform-staging:
    name: '📦 Deploy - Staging'
    runs-on: ubuntu-20.04
    needs: ['build']
    environment:
      name: SANDBOX
      url: "https://resume-staging.lvk.sh"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
    - name: Dump Kubeconfig file
      run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config && KUBECONFIG=~/.kube/config
      working-directory: terraform

    - name: Terraform Init
      run: terraform init --backend-config=${{ secrets.TERRAFORM_CONFIG }}
      working-directory: terraform

    - name: Terraform Plan
      run: export TF_VAR_container="${{ env.PACKAGE_NAME }}:$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')" && terraform plan
      working-directory: terraform
      env:
        TF_VAR_prefix: ${{ secrets.PREFIX }}
        TF_VAR_deployurl: ${{ secrets.DEPLOY_URL }}

    - name: Terraform Apply
      run: export TF_VAR_container="${{ env.PACKAGE_NAME }}:$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')" && terraform apply -auto-approve
      working-directory: terraform
      env:
        TF_VAR_prefix: ${{ secrets.PREFIX }}
        TF_VAR_deployurl: ${{ secrets.DEPLOY_URL }}

  validate-staging:
    name: '✔️ Validate Deployment'
    runs-on: ubuntu-20.04
    needs: ['terraform-staging']
    environment:
      name: SANDBOX
    steps:
    - name: Check that the page has been deployed successfully
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: "https://${{ secrets.DEPLOY_URL }}"
        follow-redirect: no
        max-attempts: 5
        retry-delay: 5s

  terraform-master:
    name: '📦 Deploy - Staging'
    runs-on: ubuntu-20.04
    needs: ['validate-staging']
    environment:
      name: PROD
      url: "https://resume.lvk.sh"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
    - name: Dump Kubeconfig file
      run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config && KUBECONFIG=~/.kube/config
      working-directory: terraform

    - name: Terraform Init
      run: terraform init --backend-config=${{ secrets.TERRAFORM_CONFIG }}
      working-directory: terraform

    - name: Terraform Plan
      run: export TF_VAR_container="${{ env.PACKAGE_NAME }}:$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')" && terraform plan
      working-directory: terraform
      env:
        TF_VAR_prefix: ${{ secrets.PREFIX }}
        TF_VAR_deployurl: ${{ secrets.DEPLOY_URL }}

    - name: Terraform Apply
      run: export TF_VAR_container="${{ env.PACKAGE_NAME }}:$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')" && terraform apply -auto-approve
      working-directory: terraform
      env:
        TF_VAR_prefix: ${{ secrets.PREFIX }}
        TF_VAR_deployurl: ${{ secrets.DEPLOY_URL }}

  validate-master:
    name: '✔️ Validate Deployment'
    runs-on: ubuntu-20.04
    needs: ['terraform-master']
    environment:
      name: PROD
    steps:
    - name: Check that the page has been deployed successfully
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: "https://${{ secrets.DEPLOY_URL }}"
        follow-redirect: no
        max-attempts: 5
        retry-delay: 5s